import Navbar from "@/components/navbar/navbar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" style={{ height: "100%", overflow: "hidden" }}>
      <body style={{ height: "calc(100vh - 12rem - 4px)", margin: 0 }}>
        <header
          style={{
            backgroundColor: "ghostwhite",
            padding: "1rem",
            height: "3rem",
            alignItems: "center",
            display: "flex",
            justifyContent: "center",
            borderBottom: "2px solid black",
          }}
        >
          <Navbar
            routes={[
              { href: "/", label: "Home" },
              { href: "/products", label: "Products" },
              { href: "/docs", label: "Docs" },
              { href: "/about", label: "About" },
            ]}
          />
        </header>
        <div
          style={{
            padding: "1rem",
            height: "100%",
            overflowY: "auto",
          }}
        >
          {children}
        </div>
        <footer
          style={{
            backgroundColor: "ghostwhite",
            padding: "1rem",
            height: "3rem",
            borderTop: "2px solid black",
            alignSelf: "flex-end",
            clear: "both",
            position: "relative",
          }}
        >
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
